version: '3.7'
services:

    yt_nginx:
        container_name: yt_nginx
        restart: unless-stopped
        build: ./nginx_server
        ports:
            - 8080:80
        expose:
            - 80
        volumes:
            - youtube_cuck_data:/data
        networks:
            - cuck   

    yt_mysql:
        container_name: yt_mysql
        image: mysql:latest
        restart: unless-stopped
        ports:
            - 3306
        expose:
            - 3306
        cap_add:
            - SYS_NICE
        environment:
            MYSQL_DATABASE: youtube_cuck
            MYSQL_ROOT_PASSWORD: password123
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - cuck
      
    yt_frontend:
        container_name: yt_frontend
        restart: unless-stopped
        build: ./flask_frontend
        ports:
            - 5010:5010
        expose:
            - 5010
        volumes:
            - youtube_cuck_data:/data
        networks:
            - cuck

    yt_backend:
        container_name: yt_backend
        restart: unless-stopped
        build: ./flask_backend
        ports:
            - 5020
        expose:
            - 5020
        volumes:
            - youtube_cuck_data:/data
        networks:
            - cuck
  
networks:
    cuck:
        driver: "bridge"

volumes:
    youtube_cuck_data:
    mysql_data: