---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-mysql
  labels:
    app: yt-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-mysql
  template:
    metadata:
      labels:
        app: yt-mysql
    spec:
      containers:
      - name: yt-mysql
        image: mysql
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yt-cuck-secrets
              key: db_root_password
        - name: MYSQL_DATABASE
          value: youtube_cuck
        ports:
        - containerPort: 3306
          name: db-container
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim


---
apiVersion: v1
kind: Service
metadata:
  name: yt-cuck-mysql
  labels:
    app: db
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mysql
  selector:
    app: yt-mysql
  type: NodePort