"""add keep field to videos

Revision ID: 9a5bfc0e48cc
Revises: 943c19b1f235
Create Date: 2023-10-21 17:39:00.460032+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a5bfc0e48cc"
down_revision: Union[str, None] = "943c19b1f235"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("youtube_video", sa.Column("keep", sa.Boolean(), nullable=True))
    op.execute("UPDATE youtube_video SET keep = 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("youtube_video", "keep")
    # ### end Alembic commands ###
