"""Added all models

Revision ID: df8424836a65
Revises:
Create Date: 2023-09-23 15:36:18.413053+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df8424836a65"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "json_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rss_feed_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playlist_video",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vid_url", sa.String(length=1000), nullable=True),
        sa.Column("vid_path", sa.String(length=1000), nullable=True),
        sa.Column("title", sa.String(length=1000), nullable=True),
        sa.Column("playlist_name", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rss_feed_date",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_human", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "youtube_video",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vid_url", sa.String(length=300), nullable=True),
        sa.Column("vid_path", sa.String(length=1000), nullable=True),
        sa.Column("thumb_url", sa.String(length=1000), nullable=True),
        sa.Column("thumb_path", sa.String(length=1000), nullable=True),
        sa.Column("pub_date", sa.Integer(), nullable=True),
        sa.Column("pub_date_human", sa.String(length=1000), nullable=True),
        sa.Column("title", sa.String(length=1000), nullable=True),
        sa.Column("views", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("channel", sa.String(length=1000), nullable=True),
        sa.Column("short", sa.Boolean(), nullable=True),
        sa.Column("livestream", sa.Boolean(), nullable=True),
        sa.Column("progress_seconds", sa.Integer(), nullable=True),
        sa.Column("inserted_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vid_url"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("youtube_video")
    op.drop_table("rss_feed_date")
    op.drop_table("playlist_video")
    op.drop_table("playlist")
    op.drop_table("json_data")
    # ### end Alembic commands ###
