"""add indexes

Revision ID: 6660e982e159
Revises: 10354a99f503
Create Date: 2023-10-01 14:54:47.507403+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6660e982e159'
down_revision: Union[str, None] = '10354a99f503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('youtube_video', 'vid_path',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index('idx_downloaded_at', 'youtube_video', ['downloaded_at'], unique=False)
    op.create_index('idx_filter_conditions', 'youtube_video', ['vid_path', 'short'], unique=False)
    op.create_index('idx_pub_date', 'youtube_video', ['pub_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pub_date', table_name='youtube_video')
    op.drop_index('idx_filter_conditions', table_name='youtube_video')
    op.drop_index('idx_downloaded_at', table_name='youtube_video')
    op.alter_column('youtube_video', 'vid_path',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
