"""add size to videos

Revision ID: 2e1c604a1cda
Revises: 6660e982e159
Create Date: 2023-10-08 11:23:20.397250+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e1c604a1cda"
down_revision: Union[str, None] = "6660e982e159"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("youtube_video", sa.Column("size", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("youtube_video", "size")
    # ### end Alembic commands ###
