"""add mostrecentvideo, mark as autoincremental

Revision ID: 943c19b1f235
Revises: 2e1c604a1cda
Create Date: 2023-10-08 19:59:14.913798+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "943c19b1f235"
down_revision: Union[str, None] = "2e1c604a1cda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "most_recent_video",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vid_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("vid_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("most_recent_video")
    # ### end Alembic commands ###
