"""Add download job table for async downloads

Revision ID: 3fed6076c66a
Revises: 979c997e319a
Create Date: 2025-08-24 23:48:53.425031+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fed6076c66a"
down_revision: Union[str, None] = "979c997e319a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "download_job",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_url", sa.String(length=300), nullable=False),
        sa.Column("video_title", sa.String(length=1000), nullable=True),
        sa.Column("channel_name", sa.String(length=1000), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("max_retries", sa.Integer(), nullable=True),
        sa.Column("video_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_download_job_created_at", "download_job", ["created_at"], unique=False
    )
    op.create_index(
        "idx_download_job_priority_status",
        "download_job",
        ["priority", "status"],
        unique=False,
    )
    op.create_index("idx_download_job_status", "download_job", ["status"], unique=False)
    op.alter_column(
        "channel", "channel_id", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "channel", "channel_url", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "channel",
        "channel_name",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "channel",
        "channel_name",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "channel",
        "channel_url",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "channel", "channel_id", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.drop_index("idx_download_job_status", table_name="download_job")
    op.drop_index("idx_download_job_priority_status", table_name="download_job")
    op.drop_index("idx_download_job_created_at", table_name="download_job")
    op.drop_table("download_job")
    # ### end Alembic commands ###
